# Generated by Django 4.1.3 on 2022-11-08 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("not specified", "not specified"),
                        ],
                        max_length=100,
                    ),
                ),
                ("age", models.IntegerField()),
                ("mobile", models.CharField(max_length=12)),
                ("address", models.TextField()),
                (
                    "usertype",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Customer", "Customer"),
                            ("Theater", "Theater"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster", models.ImageField(upload_to="")),
                ("movie_name", models.CharField(max_length=100)),
                (
                    "play_time",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Noon", "Noon"),
                            ("1st", "1st"),
                            ("2nd", "2nd"),
                        ],
                        max_length=120,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theater_name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=50)),
                ("image", models.ImageField(max_length=120, null=True, upload_to="")),
                ("email_id", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "theater_status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        max_length=50,
                    ),
                ),
                (
                    "owner_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.baseuser"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("play_time", models.DateTimeField(auto_now_add=True)),
                ("TotalBooking", models.PositiveIntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.movie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_name", models.CharField(max_length=100, unique=True)),
                ("entry_fee", models.IntegerField()),
                (
                    "screen_status",
                    models.CharField(
                        choices=[
                            ("empty", "empty"),
                            ("filling", "filling"),
                            ("Housefull", "Housefull"),
                            ("cancelled", "cancelled"),
                        ],
                        default="empty",
                        max_length=120,
                    ),
                ),
                ("total_seats", models.IntegerField()),
                (
                    "Theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.theater"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="screen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Admin.screen"
            ),
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("play_date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.baseuser"
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.show"
                    ),
                ),
            ],
        ),
    ]
