# Generated by Django 4.1.4 on 2023-08-19 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Theater', '0003_movie_screen_show_movie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('1st', '1st'), ('2nd', '2nd')], max_length=120)),
                ('occupancy', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theater.screen')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theater.show')),
            ],
        ),
    ]
