# Generated by Django 4.1.2 on 2022-11-24 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Theater", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "play_time",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Noon", "Noon"),
                            ("1st", "1st"),
                            ("2nd", "2nd"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "available_seats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Theater.screen"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Theater.show"
                    ),
                ),
            ],
        ),
    ]
