# Generated by Django 4.1.2 on 2022-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="occupancy",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
