# Generated by Django 4.1.2 on 2022-11-28 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0002_bookingrequest_occupancy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingrequest",
            old_name="available_seats",
            new_name="screen",
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="occupancy",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
