# Generated by Django 4.1.3 on 2022-11-09 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster", models.ImageField(null=True, upload_to="images")),
                ("movie_name", models.CharField(max_length=100)),
                (
                    "play_time",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Noon", "Noon"),
                            ("1st", "1st"),
                            ("2nd", "2nd"),
                        ],
                        max_length=120,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theater_name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=50)),
                ("image", models.ImageField(null=True, upload_to="images")),
                (
                    "email_id",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email_address"
                    ),
                ),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "theater_status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        max_length=50,
                    ),
                ),
                (
                    "owner_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("play_time", models.DateTimeField(auto_now_add=True)),
                ("TotalBooking", models.PositiveIntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Theater.movie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_name", models.CharField(max_length=100, unique=True)),
                ("entry_fee", models.IntegerField()),
                (
                    "screen_status",
                    models.CharField(
                        choices=[
                            ("empty", "empty"),
                            ("filling", "filling"),
                            ("Housefull", "Housefull"),
                            ("cancelled", "cancelled"),
                        ],
                        default="empty",
                        max_length=120,
                    ),
                ),
                ("total_seats", models.IntegerField()),
                (
                    "Theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Theater.theater",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="screen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Theater.screen"
            ),
        ),
    ]
