# Generated by Django 4.1.4 on 2023-08-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theatreowned', to='Theater.theater'),
            preserve_default=False,
        ),
    ]
