# Generated by Django 4.1.3 on 2022-11-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="theater",
            name="approval",
            field=models.BooleanField(default=False, verbose_name="Approval"),
        ),
    ]
