# Generated by Django 4.1.3 on 2022-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='screen_status',
            field=models.CharField(choices=[('empty', 'empty'), ('filling', 'filling'), ('almostfull', 'almostfull'), ('housefull', 'housefull'), ('cancelled', 'cancelled')], default='empty', max_length=120),
        ),
    ]
