# Generated by Django 4.1.4 on 2023-08-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Theater', '0002_screen_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Theater.screen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Theater.movie'),
            preserve_default=False,
        ),
    ]
