# Generated by Django 4.1.3 on 2022-11-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theater", "0002_theater_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="theater",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
