# Generated by Django 4.1.3 on 2022-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theater", "0002_alter_theater_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screen",
            old_name="Theater",
            new_name="theater",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="screen_status",
        ),
        migrations.AddField(
            model_name="show",
            name="screen_status",
            field=models.CharField(
                choices=[
                    ("empty", "empty"),
                    ("filling", "filling"),
                    ("Housefull", "Housefull"),
                    ("cancelled", "cancelled"),
                ],
                default="empty",
                max_length=120,
            ),
        ),
    ]
