# Generated by Django 4.1.3 on 2022-11-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theater", "0004_alter_screen_entry_fee_alter_screen_total_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="theater",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
