# Generated by Django 4.1.3 on 2022-11-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Theater", "0005_theater_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="screen",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Theater.screen"
            ),
        ),
    ]
